class Method():
    def __init__(self, name):
        self.name = name
        self.real_name = name
        self.type = []
        self.param_list = {}
        self.call_list = []
        self.var_list = []
        self.taint_list = []
        self.for_list = []
        self.array_access_list = {}
        self.string_list = []
        self.visibility = ''
        self.static = False
        self.real_name = name
        self.real_class = ''
        self.real_file = ''
        self.code = ''
        self.namespace = ''
        self.uses = {}